export interface SapQuotationsResponse {
  'odata.metadata': string;
  value: SapQuotationsRaw[];
}

export interface SapQuotationsRaw {
  'odata.etag': string;
  DocEntry: number;
  DocNum: number;
  DocType: string;
  HandWritten: string;
  Printed: string;
  DocDate: Date;
  DocDueDate: Date;
  CardCode: string;
  CardName: string;
  Address: string;
  NumAtCard: string | number | null;
  DocTotal: number;
  AttachmentEntry: string | number | null;
  DocCurrency: string;
  DocRate: number;
  Reference1: string;
  Reference2: string | number | null;
  Comments: string | number | null;
  JournalMemo: string;
  PaymentGroupCode: number;
  DocTime: string;
  SalesPersonCode: number;
  TransportationCode: number;
  Confirmed: string;
  ImportFileNum: string | number | null;
  SummeryType: string;
  ContactPersonCode: number;
  ShowSCN: string;
  Series: number;
  TaxDate: Date;
  PartialSupply: string;
  DocObjectCode: string;
  ShipToCode: string;
  Indicator: string | number | null;
  FederalTaxID: string;
  DiscountPercent: number;
  PaymentReference: string | number | null;
  CreationDate: Date;
  UpdateDate: Date;
  FinancialPeriod: number;
  UserSign: number;
  TransNum: string | number | null;
  VatSum: number;
  VatSumSys: number;
  VatSumFc: number;
  NetProcedure: string;
  DocTotalFc: number;
  DocTotalSys: number;
  Form1099: string | number | null;
  Box1099: string | number | null;
  RevisionPo: string;
  RequriedDate: string | number | null;
  CancelDate: string | number | null;
  BlockDunning: string;
  Submitted: string;
  Segment: number;
  PickStatus: string;
  Pick: string;
  PaymentMethod: string;
  PaymentBlock: string;
  PaymentBlockEntry: string | number | null;
  CentralBankIndicator: string | number | null;
  MaximumCashDiscount: string;
  Reserve: string;
  Project: string | number | null;
  ExemptionValidityDateFrom: string | number | null;
  ExemptionValidityDateTo: string | number | null;
  WareHouseUpdateType: string;
  Rounding: string;
  ExternalCorrectedDocNum: string | number | null;
  InternalCorrectedDocNum: string | number | null;
  NextCorrectingDocument: string | number | null;
  DeferredTax: string;
  TaxExemptionLetterNum: string | number | null;
  WTApplied: number;
  WTAppliedFC: number;
  BillOfExchangeReserved: string;
  AgentCode: string | number | null;
  WTAppliedSC: number;
  TotalEqualizationTax: number;
  TotalEqualizationTaxFC: number;
  TotalEqualizationTaxSC: number;
  NumberOfInstallments: number;
  ApplyTaxOnFirstInstallment: string;
  TaxOnInstallments: string;
  WTNonSubjectAmount: number;
  WTNonSubjectAmountSC: number;
  WTNonSubjectAmountFC: number;
  WTExemptedAmount: number;
  WTExemptedAmountSC: number;
  WTExemptedAmountFC: number;
  BaseAmount: number;
  BaseAmountSC: number;
  BaseAmountFC: number;
  WTAmount: number;
  WTAmountSC: number;
  WTAmountFC: number;
  VatDate: string | number | null;
  DocumentsOwner: string | number | null;
  FolioPrefixString: string | number | null;
  FolioNumber: string | number | null;
  DocumentSubType: string;
  BPChannelCode: string | number | null;
  BPChannelContact: string | number | null;
  Address2: string;
  DocumentStatus: string;
  PeriodIndicator: string;
  PayToCode: string;
  ManualNumber: string | number | null;
  UseShpdGoodsAct: string;
  IsPayToBank: string;
  PayToBankCountry: string | number | null;
  PayToBankCode: string | number | null;
  PayToBankAccountNo: string | number | null;
  PayToBankBranch: string | number | null;
  BPL_IDAssignedToInvoice: string | number | null;
  DownPayment: number;
  ReserveInvoice: string;
  LanguageCode: number;
  TrackingNumber: string | number | null;
  PickRemark: string | number | null;
  ClosingDate: string | number | null;
  SequenceCode: string | number | null;
  SequenceSerial: string | number | null;
  SeriesString: string | number | null;
  SubSeriesString: string | number | null;
  SequenceModel: string;
  UseCorrectionVATGroup: string;
  TotalDiscount: number;
  DownPaymentAmount: number;
  DownPaymentPercentage: number;
  DownPaymentType: string;
  DownPaymentAmountSC: number;
  DownPaymentAmountFC: number;
  VatPercent: number;
  ServiceGrossProfitPercent: string | number | null;
  OpeningRemarks: string | number | null;
  ClosingRemarks: string | number | null;
  RoundingDiffAmount: number;
  RoundingDiffAmountFC: number;
  RoundingDiffAmountSC: number;
  Cancelled: string;
  SignatureInputMessage: string | number | null;
  SignatureDigest: string | number | null;
  CertificationNumber: string | number | null;
  PrivateKeyVersion: string | number | null;
  ControlAccount: string;
  InsuranceOperation347: string;
  ArchiveNonremovableSalesQuotation: string;
  GTSChecker: string | number | null;
  GTSPayee: string | number | null;
  ExtraMonth: number;
  ExtraDays: number;
  CashDiscountDateOffset: number;
  StartFrom: string;
  NTSApproved: string;
  ETaxWebSite: string | number | null;
  ETaxNumber: string | number | null;
  NTSApprovedNumber: string | number | null;
  EDocGenerationType: string;
  EDocSeries: string | number | null;
  EDocNum: string | number | null;
  EDocExportFormat: string | number | null;
  EDocStatus: string;
  EDocErrorCode: string | number | null;
  EDocErrorMessage: string | number | null;
  DownPaymentStatus: string;
  GroupSeries: string | number | null;
  GroupNumber: string | number | null;
  GroupHandWritten: string;
  ReopenOriginalDocument: string | number | null;
  ReopenManuallyClosedOrCanceledDocument: string | number | null;
  CreateOnlineQuotation: string;
  POSEquipmentNumber: string | number | null;
  POSManufacturerSerialNumber: string | number | null;
  POSCashierNumber: string | number | null;
  ApplyCurrentVATRatesForDownPaymentsToDraw: string;
  ClosingOption: string;
  SpecifiedClosingDate: string | number | null;
  OpenForLandedCosts: string;
  AuthorizationStatus: string;
  TotalDiscountFC: number;
  TotalDiscountSC: number;
  RelevantToGTS: string;
  BPLName: string | number | null;
  VATRegNum: string | number | null;
  AnnualInvoiceDeclarationReference: string | number | null;
  Supplier: string | number | null;
  Releaser: string | number | null;
  Receiver: string | number | null;
  BlanketAgreementNumber: string | number | null;
  IsAlteration: string;
  CancelStatus: string;
  AssetValueDate: string | number | null;
  DocumentDelivery: string;
  AuthorizationCode: string | number | null;
  StartDeliveryDate: string | number | null;
  StartDeliveryTime: string | number | null;
  EndDeliveryDate: string | number | null;
  EndDeliveryTime: string | number | null;
  VehiclePlate: string | number | null;
  ATDocumentType: string | number | null;
  ElecCommStatus: string | number | null;
  ElecCommMessage: string | number | null;
  ReuseDocumentNum: string;
  ReuseNotaFiscalNum: string;
  PrintSEPADirect: string;
  FiscalDocNum: string | number | null;
  POSDailySummaryNo: string | number | null;
  POSReceiptNo: string | number | null;
  PointOfIssueCode: string | number | null;
  Letter: string | number | null;
  FolioNumberFrom: string | number | null;
  FolioNumberTo: string | number | null;
  InterimType: string;
  RelatedType: number;
  RelatedEntry: string | number | null;
  SAPPassport: string | number | null;
  DocumentTaxID: string | number | null;
  DateOfReportingControlStatementVAT: string | number | null;
  ReportingSectionControlStatementVAT: string | number | null;
  ExcludeFromTaxReportControlStatementVAT: string;
  POS_CashRegister: string | number | null;
  UpdateTime: string;
  CreateQRCodeFrom: string | number | null;
  PriceMode: string | number | null;
  ShipFrom: string;
  CommissionTrade: string;
  CommissionTradeReturn: string;
  UseBillToAddrToDetermineTax: string;
  Cig: string | number | null;
  Cup: string | number | null;
  FatherCard: string | number | null;
  FatherType: string;
  ShipState: string | number | null;
  ShipPlace: string | number | null;
  CustOffice: string | number | null;
  FCI: string | number | null;
  AddLegIn: string | number | null;
  LegTextF: string | number | null;
  DANFELgTxt: string | number | null;
  IndFinal: string;
  DataVersion: number;
  LastPageFolioNumber: string | number | null;
  InventoryStatus: string;
  PlasticPackagingTaxRelevant: string;
  NotRelevantForMonthlyInvoice: string;
  U_BPCOST: string | number | null;
  U_OK1_IFRS: string;
  U_DocEntryLeg: string | number | null;
  U_idLineLeg: string | number | null;
  U_serieLeg: string | number | null;
  U_Autorret: string;
  U_WUID: string | number | null;
  U_BodegaDestino: string | number | null;
  U_Traslado: string;
  U_PrjctT: string | number | null;
  U_Dim1T: string | number | null;
  U_Dim2T: string | number | null;
  U_Dim3T: string | number | null;
  U_addInFaElectronica_tipoND_FE: string;
  U_tipoNCC_FE: string;
  U_fechaDocCont: string | number | null;
  U_FE_FechaTC: string | number | null;
  U_condEntrega_FE: string;
  U_Doc_CR_FE: string | number | null;
  U_CUFE: string | number | null;
  U_DocAdicionales: string;
  U_addInFE_LinkFE: string | number | null;
  U_addInFa_FVSerie: string | number | null;
  U_addInFa_FVNum: string | number | null;
  U_NroFacContinFE: string | number | null;
  U_tipoEmisionFE: string;
  U_INCOTERMS: string | number | null;
  U_MedioPg: string;
  U_OK1_Fa_Export: string;
  U_Plantilla: number;
  U_CodigoQR: string | number | null;
  U_SelloDigital: string | number | null;
  U_TipoFacturacion: string;
  U_tipoMandato: string;
  U_tipoTransporte: string;
  U_tipo_NCV_FE: string;
  U_tipo_NDV_FE: string;
  U_formaGeneracion: string;
  U_conceptoCorreccionNC: string;
  U_Dim4T: string | number | null;
  U_Dim5T: string | number | null;
  U_AIU_ADMIN: number;
  U_AIU_IMPRE: number;
  U_AIU_UTIL: number;
  U_TipoNota: string | number | null;
  U_Saneamiento: string;
  U_totalImpoCo: number;
  U_OK1_IVAPA: string;
  U_noConReq: string | number | null;
  U_Retefue: string;
  U_ReteIca: string;
  U_CatRet: string | number | null;
  U_EsIndep: string;
  U_periodoAsociado_FE: string | number | null;
  U_CSS_CruceAnticipo: string;
  U_CSS_TipoAjusteInv: string;
  U_CSS_PuertoOrigen: string;
  U_CSS_PuertoDestino: string;
  U_CSS_TipoCarga: string;
  U_CSS_TipoContenedor: string;
  U_CSS_TipoTransporte: string;
  U_CSS_FecEmbarque: string | number | null;
  U_CSS_FecLlegada: string | number | null;
  U_CSS_Naviera: string | number | null;
  U_CSS_NombreBuque: string | number | null;
  U_CSS_NroContenedor: string | number | null;
  U_CSS_NroBL: string | number | null;
  U_CSS_Operador: string;
  U_CSS_NroDeclaracion: string | number | null;
  U_CSS_EdoEmbarque: string;
  U_CodCaja: string | number | null;
  U_NumBase: string | number | null;
  U_BCO_NDO: string | number | null;
  U_USER_AUTORIZA: string | number | null;
  U_USER_SOLICITA: string | number | null;
  U_ESTADO_SOLICITUD: string;
  U_MOTIVO_RECHAZO: string | number | null;
  U_IDSoliApp: string | number | null;
  U_FromWhsCod: string | number | null;
  U_MetodoPWeb: string | number | null;
  U_numReqWeb: string | number | null;
  U_SplCode: string | number | null;
  U_OK1_DescReq: string | number | null;
  U_OrderShopify: string | number | null;
  U_NameOrdenShopify: string | number | null;
  Document_ApprovalRequests: any[];
  DocumentLines: DocumentLine[];
  ElectronicProtocols: any[];
  DocumentAdditionalExpenses: any[];
  DocumentSpecialLines: any[];
  TaxExtension: TaxExtension;
  AddressExtension: AddressExtension;
  DocumentReferences: any[];
}

export interface AddressExtension {
  ShipToStreet: string;
  ShipToStreetNo: string | number | null;
  ShipToBlock: string;
  ShipToBuilding: string | number | null;
  ShipToCity: string;
  ShipToZipCode: string | number | null;
  ShipToCounty: string | number | null;
  ShipToState: string;
  ShipToCountry: string;
  ShipToAddressType: string | number | null;
  BillToStreet: string;
  BillToStreetNo: string | number | null;
  BillToBlock: string;
  BillToBuilding: string | number | null;
  BillToCity: string;
  BillToZipCode: string | number | null;
  BillToCounty: string | number | null;
  BillToState: string;
  BillToCountry: string;
  BillToAddressType: string | number | null;
  ShipToGlobalLocationNumber: string | number | null;
  BillToGlobalLocationNumber: string | number | null;
  ShipToAddress2: string | number | null;
  ShipToAddress3: string | number | null;
  BillToAddress2: string | number | null;
  BillToAddress3: string | number | null;
  PlaceOfSupply: string | number | null;
  PurchasePlaceOfSupply: string | number | null;
  DocEntry: number;
  GoodsIssuePlaceBP: string | number | null;
  GoodsIssuePlaceCNPJ: string | number | null;
  GoodsIssuePlaceCPF: string | number | null;
  GoodsIssuePlaceStreet: string | number | null;
  GoodsIssuePlaceStreetNo: string | number | null;
  GoodsIssuePlaceBuilding: string | number | null;
  GoodsIssuePlaceZip: string | number | null;
  GoodsIssuePlaceBlock: string | number | null;
  GoodsIssuePlaceCity: string | number | null;
  GoodsIssuePlaceCounty: string | number | null;
  GoodsIssuePlaceState: string | number | null;
  GoodsIssuePlaceCountry: string | number | null;
  GoodsIssuePlacePhone: string | number | null;
  GoodsIssuePlaceEMail: string | number | null;
  GoodsIssuePlaceDepartureDate: string | number | null;
  DeliveryPlaceBP: string | number | null;
  DeliveryPlaceCNPJ: string | number | null;
  DeliveryPlaceCPF: string | number | null;
  DeliveryPlaceStreet: string | number | null;
  DeliveryPlaceStreetNo: string | number | null;
  DeliveryPlaceBuilding: string | number | null;
  DeliveryPlaceZip: string | number | null;
  DeliveryPlaceBlock: string | number | null;
  DeliveryPlaceCity: string | number | null;
  DeliveryPlaceCounty: string | number | null;
  DeliveryPlaceState: string | number | null;
  DeliveryPlaceCountry: string | number | null;
  DeliveryPlacePhone: string | number | null;
  DeliveryPlaceEMail: string | number | null;
  DeliveryPlaceDepartureDate: string | number | null;
  U_MunicipioS: string;
  U_MunicipioB: string;
  U_CodDepartamentoS: string | number | null;
  U_CodDepartamentoB: string | number | null;
}

export interface DocumentLine {
  LineNum: number;
  ItemCode: string;
  ItemDescription: string;
  Quantity: number;
  ShipDate: string | number | null;
  Price: number;
  PriceAfterVAT: number;
  Currency: string;
  Rate: number;
  DiscountPercent: number;
  VendorNum: string;
  SerialNum: string | number | null;
  WarehouseCode: string;
  SalesPersonCode: number;
  CommisionPercent: number;
  TreeType: string;
  AccountCode: string;
  UseBaseUnits: string;
  SupplierCatNum: string;
  CostingCode: string;
  ProjectCode: string | number | null;
  BarCode: string | number | null;
  VatGroup: string;
  Height1: number;
  Hight1Unit: string | number | null;
  Height2: number;
  Height2Unit: string | number | null;
  Lengh1: number;
  Lengh1Unit: string | number | null;
  Lengh2: number;
  Lengh2Unit: string | number | null;
  Weight1: number;
  Weight1Unit: string | number | null;
  Weight2: number;
  Weight2Unit: string | number | null;
  Factor1: number;
  Factor2: number;
  Factor3: number;
  Factor4: number;
  BaseType: number;
  BaseEntry: string | number | null;
  BaseLine: string | number | null;
  Volume: number;
  VolumeUnit: number;
  Width1: number;
  Width1Unit: string | number | null;
  Width2: number;
  Width2Unit: string | number | null;
  Address: string;
  TaxCode: string;
  TaxType: string;
  TaxLiable: string;
  PickStatus: string;
  PickQuantity: number;
  PickListIdNumber: string | number | null;
  OriginalItem: string | number | null;
  BackOrder: string | number | null;
  FreeText: string;
  ShippingMethod: number;
  POTargetNum: string | number | null;
  POTargetEntry: string;
  POTargetRowNum: string | number | null;
  CorrectionInvoiceItem: string;
  CorrInvAmountToStock: number;
  CorrInvAmountToDiffAcct: number;
  AppliedTax: number;
  AppliedTaxFC: number;
  AppliedTaxSC: number;
  WTLiable: string;
  DeferredTax: string;
  EqualizationTaxPercent: number;
  TotalEqualizationTax: number;
  TotalEqualizationTaxFC: number;
  TotalEqualizationTaxSC: number;
  NetTaxAmount: number;
  NetTaxAmountFC: number;
  NetTaxAmountSC: number;
  MeasureUnit: string;
  UnitsOfMeasurment: number;
  LineTotal: number;
  TaxPercentagePerRow: number;
  TaxTotal: number;
  ConsumerSalesForecast: string;
  ExciseAmount: number;
  TaxPerUnit: number;
  TotalInclTax: number;
  CountryOrg: string | number | null;
  SWW: string;
  TransactionType: string | number | null;
  DistributeExpense: string;
  RowTotalFC: number;
  RowTotalSC: number;
  LastBuyInmPrice: number;
  LastBuyDistributeSumFc: number;
  LastBuyDistributeSumSc: number;
  LastBuyDistributeSum: number;
  StockDistributesumForeign: number;
  StockDistributesumSystem: number;
  StockDistributesum: number;
  StockInmPrice: number;
  PickStatusEx: string;
  TaxBeforeDPM: number;
  TaxBeforeDPMFC: number;
  TaxBeforeDPMSC: number;
  CFOPCode: string | number | null;
  CSTCode: string | number | null;
  Usage: string | number | null;
  TaxOnly: string;
  VisualOrder: number;
  BaseOpenQuantity: number;
  UnitPrice: number;
  LineStatus: string;
  PackageQuantity: number;
  Text: string;
  LineType: string;
  COGSCostingCode: string;
  COGSAccountCode: string;
  ChangeAssemlyBoMWarehouse: string;
  GrossBuyPrice: number;
  GrossBase: number;
  GrossProfitTotalBasePrice: number;
  CostingCode2: string;
  CostingCode3: string | number | null;
  CostingCode4: string;
  CostingCode5: string;
  ItemDetails: string | number | null;
  LocationCode: string | number | null;
  ActualDeliveryDate: string | number | null;
  RemainingOpenQuantity: number;
  OpenAmount: number;
  OpenAmountFC: number;
  OpenAmountSC: number;
  ExLineNo: string | number | null;
  RequiredDate: string | number | null;
  RequiredQuantity: number;
  COGSCostingCode2: string;
  COGSCostingCode3: string;
  COGSCostingCode4: string;
  COGSCostingCode5: string;
  CSTforIPI: string | number | null;
  CSTforPIS: string | number | null;
  CSTforCOFINS: string | number | null;
  CreditOriginCode: string | number | null;
  WithoutInventoryMovement: string;
  AgreementNo: string | number | null;
  AgreementRowNumber: string | number | null;
  ActualBaseEntry: string | number | null;
  ActualBaseLine: string | number | null;
  DocEntry: number;
  Surpluses: number;
  DefectAndBreakup: number;
  Shortages: number;
  ConsiderQuantity: string;
  PartialRetirement: string;
  RetirementQuantity: number;
  RetirementAPC: number;
  ThirdParty: string;
  PoNum: string | number | null;
  PoItmNum: string | number | null;
  ExpenseType: string | number | null;
  ReceiptNumber: string | number | null;
  ExpenseOperationType: string | number | null;
  FederalTaxID: string | number | null;
  GrossProfit: number;
  GrossProfitFC: number;
  GrossProfitSC: number;
  PriceSource: string;
  StgSeqNum: string | number | null;
  StgEntry: string | number | null;
  StgDesc: string | number | null;
  UoMEntry: number;
  UoMCode: string;
  InventoryQuantity: number;
  RemainingOpenInventoryQuantity: number;
  ParentLineNum: string | number | null;
  Incoterms: number;
  TransportMode: number;
  NatureOfTransaction: string | number | null;
  DestinationCountryForImport: string | number | null;
  DestinationRegionForImport: string | number | null;
  OriginCountryForExport: string | number | null;
  OriginRegionForExport: string | number | null;
  ItemType: string;
  ChangeInventoryQuantityIndependently: string;
  FreeOfChargeBP: string;
  SACEntry: string | number | null;
  HSNEntry: string | number | null;
  GrossPrice: number;
  GrossTotal: number;
  GrossTotalFC: number;
  GrossTotalSC: number;
  NCMCode: number;
  NVECode: string | number | null;
  IndEscala: string;
  CtrSealQty: number;
  CNJPMan: string | number | null;
  CESTCode: number;
  UFFiscalBenefitCode: string | number | null;
  ReverseCharge: string;
  ShipToCode: string;
  ShipToDescription: string;
  OwnerCode: string | number | null;
  ExternalCalcTaxRate: number;
  ExternalCalcTaxAmount: number;
  ExternalCalcTaxAmountFC: number;
  ExternalCalcTaxAmountSC: number;
  StandardItemIdentification: number;
  CommodityClassification: number;
  WeightOfRecycledPlastic: number;
  PlasticPackageExemptionReason: string | number | null;
  LegalText: string | number | null;
  Cig: string | number | null;
  Cup: string | number | null;
  UnencumberedReason: string | number | null;
  CUSplit: string;
  ListNum: string | number | null;
  RecognizedTaxCode: string | number | null;
  U_Location: string | number | null;
  U_CalcAIU: string;
  U_Marca: string;
  U_Modelo: string;
  U_IVCDone: string;
  U_RILDone: string;
  U_valor_ImpoCon: number;
  U_CSS_PartArancelaria: string | number | null;
  U_CSS_Sincronizado: string;
  U_DocumentoEvaluado: string;
  U_CreateDate: string | number | null;
  U_DeliveryDate: string | number | null;
  U_OK1_DescReqL: string | number | null;
  U_mesesDiferidoL: string | number | null;
  U_DocNumBase: string | number | null;
  U_ObjType: string | number | null;
  U_CSS_AddrLineNum: string | number | null;
  LineTaxJurisdictions: LineTaxJurisdiction[];
  DocumentLineAdditionalExpenses: any[];
}

export interface LineTaxJurisdiction {
  JurisdictionCode: string;
  JurisdictionType: number;
  TaxAmount: number;
  TaxAmountSC: number;
  TaxAmountFC: number;
  TaxRate: number;
  DocEntry: number;
  LineNumber: number;
  RowSequence: number;
  ExternalCalcTaxRate: number;
  ExternalCalcTaxAmount: number;
  ExternalCalcTaxAmountFC: number;
  ExternalCalcTaxAmountSC: number;
  BaseSum: number;
  TaxInPrice: string;
  NonDeductiblePercent: number;
  TaxOnReserveInvoice: string;
  Exempt: string;
  Unencumbered: string;
}

export interface TaxExtension {
  TaxId0: string | number | null;
  TaxId1: string | number | null;
  TaxId2: string | number | null;
  TaxId3: string | number | null;
  TaxId4: string | number | null;
  TaxId5: string | number | null;
  TaxId6: string | number | null;
  TaxId7: string | number | null;
  TaxId8: string | number | null;
  TaxId9: string | number | null;
  State: string | number | null;
  County: string | number | null;
  Incoterms: string | number | null;
  Vehicle: string | number | null;
  VehicleState: string | number | null;
  NFRef: string | number | null;
  Carrier: string | number | null;
  PackQuantity: string | number | null;
  PackDescription: string | number | null;
  Brand: string | number | null;
  ShipUnitNo: string | number | null;
  NetWeight: number;
  GrossWeight: number;
  StreetS: string;
  BlockS: string;
  BuildingS: string | number | null;
  CityS: string;
  ZipCodeS: string | number | null;
  CountyS: string | number | null;
  StateS: string;
  CountryS: string;
  StreetB: string;
  BlockB: string;
  BuildingB: string | number | null;
  CityB: string;
  ZipCodeB: string | number | null;
  CountyB: string | number | null;
  StateB: string;
  CountryB: string;
  ImportOrExport: string | number | null;
  MainUsage: string | number | null;
  GlobalLocationNumberS: string | number | null;
  GlobalLocationNumberB: string | number | null;
  TaxId12: string | number | null;
  TaxId13: string | number | null;
  BillOfEntryNo: string | number | null;
  BillOfEntryDate: string | number | null;
  OriginalBillOfEntryNo: string | number | null;
  OriginalBillOfEntryDate: string | number | null;
  ImportOrExportType: string;
  PortCode: string | number | null;
  DocEntry: number;
  BoEValue: number;
  ClaimRefund: string | number | null;
  DifferentialOfTaxRate: string | number | null;
  IsIGSTAccount: string | number | null;
  TaxId14: string | number | null;
}
